### ISSUE TITLE
ModuleNotFoundError when launching the web server

### ISSUE THREAD

**Issue by beauthi** [ANSSI-FR/SecuML#14]
Hello,

I tried installing the module in a virtualenv, as mentionned in the docs. Everything works fine until I launch the web server with the following command :
`SecuML_server --secuml-conf conf.yml`
My `conf.yml` file looks like this :
```
input_data_dir: '/var/dataset.csv'
output_data_dir: '/var/results/'
db_uri: 'postgresql://user:password@localhost/secuml'
```
The error I get is the following :
```
Traceback (most recent call last):
  File "/var/SecuML/venv/bin/SecuML_server", line 4, in <module>
    __import__('pkg_resources').run_script('SecuML==0.12', 'SecuML_server')
  File "/var/SecuML/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 658, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/var/SecuML/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1438, in run_script
    exec(code, namespace, namespace)
  File "/var/SecuML/venv/lib/python3.6/site-packages/SecuML-0.12-py3.6.egg/EGG-INFO/scripts/SecuML_server", line 53, in <module>
    import secuml.web.views
  File "/var/SecuML/venv/lib/python3.6/site-packages/SecuML-0.12-py3.6.egg/secuml/web/views/__init__.py", line 18, in <module>
    from .active_learning import active_learning  # NOQA
  File "/var/SecuML/venv/lib/python3.6/site-packages/SecuML-0.12-py3.6.egg/secuml/web/views/active_learning/active_learning.py", line 30, in <module>
    from secuml.exp.active_learning import ActiveLearningExp  # NOQA
  File "/var/SecuML/venv/lib/python3.6/site-packages/SecuML-0.12-py3.6.egg/secuml/exp/active_learning/__init__.py", line 30, in <module>
    from .iteration import Iteration
  File "/var/SecuML/venv/lib/python3.6/site-packages/SecuML-0.12-py3.6.egg/secuml/exp/active_learning/iteration.py", line 26, in <module>
    from .monitoring.exec_times import ExecutionTimesMonitoring
ModuleNotFoundError: No module named 'secuml.exp.active_learning.monitoring'
```

Thank you

**Comment by ab-anssi** [comment]
Which OS do you use ? Which version ?

**Comment by ab-anssi** [comment]
The problem is that I have recently updated the documentation. Before the installation command was `pip install -e <path_to_SecuML>`. I thought the `-e` (`--editable`) was useless when you are not updating the code. However, when you install SecuML without this option (`pip install <path_to_SecuML>`) `__init__.py` files are required in all the packages.

As a quick fix you can install SecuML with the following command line : `pip install -e <path_to_SecuML>`. I will update the code soon to add the missing `__init__.py` files.

**Comment by beauthi** [comment]
> Which OS do you use ? Which version ?

Ubuntu 18.04.2 LTS

> The problem is that I have recently updated the documentation. Before the installation command was `pip install -e <path_to_SecuML>`. I thought the `-e` (`--editable`) was useless when you are not updating the code. However, when you install SecuML without this option (`pip install <path_to_SecuML>`) `__init__.py` files are required in all the packages.
> 
> As a quick fix you can install SecuML with the following command line : `pip install -e <path_to_SecuML>`. I will update the code soon to add the missing `__init__.py` files.

Thank you very much
